name: gsheet.action test

on:
  push

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Update Google Sheet
        id: update_worksheet
        uses: jroehl/gsheet.action@v2.0.0
        with:
          spreadsheetId: 1tXO_vjGR6O7b0MQ1NZRvtZvqkHoHPDlw_MnMo8eyyJA
          commands: |
            [
              { "command": "updateData", "args": {
                  "worksheetTitle": "Integrations",
                  "data": [["Integration Name", "Repository URL", "Categories", "Submitted By", "PR URL", "Date"]]
              }},
              { "command": "getData", "args": { "range": "'Integrations'!A1:F1" } }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}

      - name: Dump results
        env:
          RESULTS: ${{ steps.update_worksheet.outputs.results }}
        run: echo "$RESULTS" | jq

      - name: Update Google Sheet Test
        id: update_test
        uses: jroehl/gsheet.action@v2.0.0
        with:
          spreadsheetId: 1tXO_vjGR6O7b0MQ1NZRvtZvqkHoHPDlw_MnMo8eyyJA
          commands: |
            [
              { "command": "updateData", "args": {
                  "worksheetTitle": "Integrations",
                  "data": [["Test Update"]]
              }}
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
